name: whatsapp-qt
base: core24
version: git
summary: Qt-based WhatsApp desktop client
description: |
  whatsapp-qt is a Qt 6 desktop client that integrates WhatsApp functionality with native
  system capabilities, including notifications and tray controls.
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  whatsapp-qt:
    command: usr/bin/WhatsApp
    plugs:
      - audio-playback
      - audio-record
      - camera
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - opengl
      - screen-inhibit-control
      - wayland
      - x11
    environment:
      # Qt platform
      QT_QPA_PLATFORM: wayland;xcb
      # Disable Qt's internal high-DPI scaling
      QT_AUTO_SCREEN_SCALE_FACTOR: '0'
      # XDG
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      # Qt WebEngine
      QTWEBENGINE_DICTIONARIES_PATH: $SNAP/usr/share/hunspell
      QTWEBENGINE_CHROMIUM_FLAGS: "--no-sandbox"

parts:
  whatsapp-qt:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_TOOLCHAIN_FILE=${CRAFT_PART_BUILD}/vcpkg/scripts/buildsystems/vcpkg.cmake
    build-packages:
      - build-essential
      - cmake
      - curl
      - git
      - ninja-build
      - pkg-config
      - python3
      - unzip
      - zip
      - qt6-base-dev
      - qt6-tools-dev
      - qt6-webengine-dev
      - libgl1-mesa-dev
    stage-packages:
      - libqt6core6t64
      - libqt6gui6
      - libqt6widgets6
      - libqt6webenginecore6
      - libqt6webenginewidgets6
      - libqt6webengine6-data
      - libqt6network6
      - libqt6dbus6
      - libqt6opengl6
      - libqt6positioning6
      - libqt6qml6
      - libqt6quick6
      - libqt6webchannel6
      - libgl1
      - libglx0
      - libglvnd0
      - libegl1
      - libgles2
      - libx11-6
      - libxcb1
      - libxkbcommon0
      - libdrm2
      - libgbm1
      - libevent-2.1-7t64
      - libfontconfig1
      - libfreetype6
      - libasound2t64
      - libpulse0
      - libnss3
      - libnspr4
      - libexpat1
      - libdbus-1-3
    build-environment:
      - VCPKG_ROOT: "${CRAFT_PART_BUILD}/vcpkg"
      - VCPKG_DEFAULT_BINARY_CACHE: "${CRAFT_PART_BUILD}/.vcpkg-cache"
      - VCPKG_FEATURE_FLAGS: manifests,manifests-allow-registries
      - VCPKG_LIBRARY_LINKAGE: static
      - CMAKE_TOOLCHAIN_FILE: "${CRAFT_PART_BUILD}/vcpkg/scripts/buildsystems/vcpkg.cmake"
    override-build: |
      set -eux
      arch="${CRAFT_ARCH_BUILD_FOR:-${CRAFT_TARGET_ARCH:-amd64}}"
      if [ "$arch" != "amd64" ]; then
        echo "Unsupported architecture: $arch" >&2
        exit 1
      fi
      export VCPKG_DEFAULT_TRIPLET="x64-linux"
      export VCPKG_DEFAULT_HOST_TRIPLET="x64-linux"
      if [ ! -d "$VCPKG_ROOT" ]; then
        git clone --depth=1 https://github.com/microsoft/vcpkg.git "$VCPKG_ROOT"
      fi
      "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
      mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"
      craftctl default
