name: whatsapp-qt
base: core24
version: git
summary: Qt-based WhatsApp desktop client
description: |
  whatsapp-qt is a Qt 6 desktop client that integrates WhatsApp functionality with native
  system capabilities, including notifications and tray controls.
grade: stable
confinement: strict

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  whatsapp-qt:
    command: usr/bin/WhatsApp
    extensions:
      - kde-neon-6
    plugs:
      - audio-playback
      - audio-record
      - camera
      - desktop
      - network
      - network-bind
      - opengl
      - screen-inhibit-control
      - wayland

parts:
  whatsapp-qt:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - build-essential
      - cmake
      - curl
      - git
      - ninja-build
      - pkg-config
      - python3
      - unzip
      - zip
    build-environment:
      - VCPKG_ROOT: "${CRAFT_PART_BUILD}/vcpkg"
      - VCPKG_DEFAULT_BINARY_CACHE: "${CRAFT_PART_BUILD}/.vcpkg-cache"
      - VCPKG_FEATURE_FLAGS: manifests,manifests-allow-registries
      - VCPKG_LIBRARY_LINKAGE: static
      - CMAKE_TOOLCHAIN_FILE: "${CRAFT_PART_BUILD}/vcpkg/scripts/buildsystems/vcpkg.cmake"
      - LD_LIBRARY_PATH: "/snap/kde-qt6-core24-sdk/current/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH:-}"
      - LDFLAGS: "-L/snap/kde-qt6-core24-sdk/current/usr/lib/x86_64-linux-gnu -Wl,-rpath-link,/snap/kde-qt6-core24-sdk/current/usr/lib/x86_64-linux-gnu"
    override-build: |
      set -eux
      arch="${CRAFT_ARCH_BUILD_FOR:-${CRAFT_TARGET_ARCH:-amd64}}"
      if [ "$arch" != "amd64" ]; then
        echo "Unsupported architecture: $arch" >&2
        exit 1
      fi
      export VCPKG_DEFAULT_TRIPLET="x64-linux"
      export VCPKG_DEFAULT_HOST_TRIPLET="x64-linux"
      if [ ! -d "$VCPKG_ROOT" ]; then
        git clone --depth=1 https://github.com/microsoft/vcpkg.git "$VCPKG_ROOT"
      fi
      "$VCPKG_ROOT/bootstrap-vcpkg.sh" -disableMetrics
      mkdir -p "$VCPKG_DEFAULT_BINARY_CACHE"
      craftctl default
